export const TECHNOLOGIES_LIST = [
  { id: 1, name: "PHP Laravel" },
  { id: 2, name: "PHP Symfony" },
  { id: 3, name: "Node.js" },
  { id: 4, name: "Express.js" },
  { id: 5, name: "NestJS" },
  { id: 6, name: "Next.js" },
  { id: 7, name: "Nuxt.js" },
  { id: 8, name: "React.js" },
  { id: 9, name: "Vue.js" },
  { id: 10, name: "Angular" },
  { id: 11, name: "Svelte" },
  { id: 12, name: "Django" },
  { id: 13, name: "Flask" },
  { id: 14, name: "FastAPI" },
  { id: 15, name: "Spring Boot" },
  { id: 16, name: "ASP.NET Core" },
  { id: 17, name: "Ruby on Rails" },
  { id: 18, name: "Golang" },
  { id: 19, name: "Rust" },
  { id: 20, name: "Java" },
  { id: 21, name: "Kotlin" },
  { id: 22, name: "Swift" },
  { id: 23, name: "Objective-C" },
  { id: 24, name: "C" },
  { id: 25, name: "C++" },
  { id: 26, name: "C#" },
  { id: 27, name: "TypeScript" },
  { id: 28, name: "JavaScript" },
  { id: 29, name: "HTML" },
  { id: 30, name: "CSS" },
  { id: 31, name: "Tailwind CSS" },
  { id: 32, name: "Bootstrap" },
  { id: 33, name: "Sass" },
  { id: 34, name: "MySQL" },
  { id: 35, name: "PostgreSQL" },
  { id: 36, name: "MongoDB" },
  { id: 37, name: "SQLite" },
  { id: 38, name: "Redis" },
  { id: 39, name: "Firebase" },
  { id: 40, name: "Supabase" },
  { id: 41, name: "Prisma" },
  { id: 42, name: "GraphQL" },
  { id: 43, name: "REST API" },
  { id: 44, name: "WebSockets" },
  { id: 45, name: "Docker" },
  { id: 46, name: "Kubernetes" },
  { id: 47, name: "Git" },
  { id: 48, name: "GitHub" },
  { id: 49, name: "GitLab" },
  { id: 50, name: "Bitbucket" },
  { id: 51, name: "AWS" },
  { id: 52, name: "Azure" },
  { id: 53, name: "Google Cloud" },
  { id: 54, name: "DigitalOcean" },
  { id: 55, name: "Render" },
  { id: 56, name: "Vercel" },
  { id: 57, name: "Netlify" },
  { id: 58, name: "RabbitMQ" },
  { id: 59, name: "Kafka" },
  { id: 60, name: "Microservices" },
  { id: 61, name: "Machine Learning" },
  { id: 62, name: "Deep Learning" },
  { id: 63, name: "TensorFlow" },
  { id: 64, name: "PyTorch" },
  { id: 65, name: "Scikit-Learn" },
  { id: 66, name: "OpenCV" },
  { id: 67, name: "Pandas" },
  { id: 68, name: "NumPy" },
  { id: 69, name: "Matplotlib" },
  { id: 70, name: "LLMs" },
  { id: 71, name: "LangChain" },
  { id: 72, name: "OpenAI API" },
  { id: 73, name: "HuggingFace" },
  { id: 74, name: "Flutter" },
  { id: 75, name: "React Native" },
  { id: 76, name: "Ionic" },
  { id: 77, name: "Android" },
  { id: 78, name: "iOS" },
  { id: 79, name: "Unity" },
  { id: 80, name: "Unreal Engine" },
  { id: 81, name: "Blender" },
  { id: 82, name: "Figma" },
  { id: 83, name: "Adobe XD" },
  { id: 84, name: "Photoshop" },
  { id: 85, name: "Illustrator" },
  { id: 86, name: "WebAssembly" },
  { id: 87, name: "Blockchain" },
  { id: 88, name: "Solidity" },
  { id: 89, name: "Hardhat" },
  { id: 90, name: "Truffle" },
  { id: 91, name: "CI/CD" },
  { id: 92, name: "Jenkins" },
  { id: 93, name: "CircleCI" },
  { id: 94, name: "Terraform" },
  { id: 95, name: "Ansible" },
  { id: 96, name: "Metaverse" },
  { id: 97, name: "AR/VR" },
  { id: 98, name: "Data Engineering" },
  { id: 99, name: "Big Data" },
  { id: 100, name: "Cybersecurity" }
];
